import { CourseData } from './types';

type Seed = { name:string; weight:string; periods:string; understanding:string; question:string; practices:string; tips:string; vocab:string[]; topics:Array<[string,string,string]> };

const seeds: Seed[] = [
 {name:'Atomic Structure and Properties',weight:'7-9%',periods:'11-14',understanding:'Macroscopic properties arise from atomic composition, electron structure, and periodic organization.',question:'How do measurements and electron structure explain the identity and behavior of matter?',practices:'Interpret particle models and spectra, use quantitative relationships, and support claims with periodic evidence.',tips:'Show dimensional analysis and connect periodic trends to Coulombic attraction.',vocab:['mole','molar mass','isotope','mass spectrum','empirical formula','electron configuration','photoelectron spectroscopy','effective nuclear charge','ionic compound'],topics:[
 ['1.1','Moles and Molar Mass','Convert among particles, moles, mass, and molar mass.'],['1.2','Mass Spectra of Elements','Interpret spectra to determine isotopic abundance and average atomic mass.'],['1.3','Elemental Composition of Pure Substances','Determine empirical composition from mass or percent data.'],['1.4','Composition of Mixtures','Determine mixture composition from measured properties.'],['1.5','Atomic Structure and Electron Configuration','Represent electron configurations and relate them to atomic structure.'],['1.6','Photoelectron Spectroscopy','Use PES data to infer binding energies and electron configurations.'],['1.7','Periodic Trends','Explain periodic trends using electrostatic attraction and shielding.'],['1.8','Valence Electrons and Ionic Compounds','Predict ion formation and ionic formulas from valence electrons.']]},
 {name:'Compound Structure and Properties',weight:'7-9%',periods:'11-14',understanding:'Bonding, geometry, and electron distribution determine compound structure and properties.',question:'How does the arrangement of atoms and electrons determine molecular behavior?',practices:'Create Lewis and particulate models, analyze potential-energy diagrams, and justify structure-property claims.',tips:'Keep bond polarity, molecular polarity, resonance, formal charge, and hybridization distinct.',vocab:['ionic bond','covalent bond','metallic bond','bond energy','lattice','alloy','Lewis diagram','resonance','formal charge','VSEPR','hybridization'],topics:[
 ['2.1','Types of Chemical Bonds','Compare ionic, covalent, and metallic bonding.'],['2.2','Intramolecular Force and Potential Energy','Relate bond length and strength to potential energy.'],['2.3','Structure of Ionic Solids','Explain ionic-solid properties using lattice structure.'],['2.4','Structure of Metals and Alloys','Explain metallic properties and compare alloy structures.'],['2.5','Lewis Diagrams','Construct Lewis diagrams using valence-electron rules.'],['2.6','Resonance and Formal Charge','Evaluate resonance contributors and formal charges.'],['2.7','VSEPR and Hybridization','Predict geometry, bond angles, polarity, and hybridization.']]},
 {name:'Properties of Substances and Mixtures',weight:'18-22%',periods:'22-27',understanding:'Intermolecular forces and particle motion explain phases, gases, solutions, separations, and spectra.',question:'How do particle attractions and motion produce observable properties?',practices:'Connect particulate and macroscopic models, analyze gas and solution data, and select separation or spectroscopic methods.',tips:'Name the particles that attract and include units in gas-law and Beer-Lambert calculations.',vocab:['intermolecular force','London dispersion force','dipole-dipole force','hydrogen bonding','ideal gas law','kinetic molecular theory','molarity','solubility','chromatography','electromagnetic spectrum','Beer-Lambert law'],topics:[
 ['3.1','Intermolecular Forces','Identify and compare intermolecular attractions.'],['3.2','Properties of Solids','Connect bonding and particle arrangement to solid properties.'],['3.3','Solids, Liquids, and Gases','Compare particle motion, spacing, and attractions across states.'],['3.4','Ideal Gas Law','Apply relationships among pressure, volume, temperature, and amount.'],['3.5','Kinetic Molecular Theory','Explain gas behavior through particle motion and collisions.'],['3.6','Deviation from Ideal Gas Law','Explain nonideal behavior using particle volume and attractions.'],['3.7','Solutions and Mixtures','Describe solution formation and calculate concentration.'],['3.8','Representations of Solutions','Translate among symbolic, particulate, and quantitative representations.'],['3.9','Separation of Solutions and Mixtures','Select and justify a separation method.'],['3.10','Solubility','Predict solubility using particle interactions.'],['3.11','Spectroscopy and the Electromagnetic Spectrum','Relate photon properties to molecular or electronic transitions.'],['3.12','Photoelectric Effect','Explain threshold frequency and electron kinetic energy.'],['3.13','Beer-Lambert Law','Use absorbance data to determine concentration.']]},
 {name:'Chemical Reactions',weight:'7-9%',periods:'11-14',understanding:'Chemical reactions rearrange atoms and transfer particles while conserving mass and charge.',question:'How can chemical transformations be represented and quantified?',practices:'Write molecular and ionic equations, interpret reaction evidence, and solve stoichiometric and titration problems.',tips:'Balance atoms and charge, include states, and connect every calculation to the balanced equation.',vocab:['net ionic equation','spectator ion','precipitate','stoichiometry','limiting reactant','titration','acid-base reaction','oxidation number','redox reaction'],topics:[
 ['4.1','Introduction for Reactions','Identify evidence and represent reactions at multiple scales.'],['4.2','Net Ionic Equations','Write complete and net ionic equations.'],['4.3','Representations of Reactions','Translate among equations, particle diagrams, and descriptions.'],['4.4','Physical and Chemical Changes','Distinguish physical and chemical changes using evidence.'],['4.5','Stoichiometry','Calculate amounts of reactants and products.'],['4.6','Introduction to Titration','Use titration data to determine an unknown concentration.'],['4.7','Types of Chemical Reactions','Classify and predict common reaction types.'],['4.8','Introduction to Acid-Base Reactions','Represent proton transfer and conjugate pairs.'],['4.9','Oxidation-Reduction Reactions','Track oxidation numbers and electron transfer.']]},
 {name:'Kinetics',weight:'7-9%',periods:'11-14',understanding:'Rates depend on collisions, mechanisms, concentration, temperature, and activation energy.',question:'What controls reaction speed and how does a mechanism produce an observed rate law?',practices:'Extract rates from data, determine rate laws, analyze mechanisms, and justify catalyst effects.',tips:'Derive rate laws from experimental data, never from the overall equation unless it is elementary.',vocab:['reaction rate','rate law','reaction order','rate constant','integrated rate law','half-life','elementary reaction','mechanism','activation energy','catalyst'],topics:[
 ['5.1','Reaction Rates','Calculate reaction rates from concentration-time data.'],['5.2','Introduction to Rate Law','Relate rate to concentration using an experimental rate law.'],['5.3','Concentration Changes Over Time','Interpret concentration-time graphs and stoichiometry.'],['5.4','Elementary Reactions','Write rate laws for elementary steps.'],['5.5','Collision Model','Explain rate changes using collision frequency, orientation, and energy.'],['5.6','Reaction Energy Profile','Interpret activation energy and energy change diagrams.'],['5.7','Introduction to Reaction Mechanisms','Combine steps and identify intermediates and catalysts.'],['5.8','Reaction Mechanism and Rate Law','Test a mechanism against an experimental rate law.'],['5.9','Pre-Equilibrium Approximation','Derive a rate law involving a fast pre-equilibrium.'],['5.10','Multistep Reaction Energy Profile','Connect transition states and intermediates to a mechanism.'],['5.11','Catalysis','Explain catalytic pathways and their effect on rate.']]},
 {name:'Thermochemistry',weight:'7-9%',periods:'11-14',understanding:'Energy transfers as heat and work; enthalpy changes can be measured and calculated.',question:'How is energy transferred and conserved during physical and chemical processes?',practices:'Analyze heating curves and calorimetry, construct energy diagrams, and calculate enthalpy.',tips:'State the system, track signs, and include everything that exchanges energy.',vocab:['system','surroundings','endothermic','exothermic','heat capacity','specific heat','calorimetry','enthalpy','Hess law','enthalpy of formation','bond enthalpy'],topics:[
 ['6.1','Endothermic and Exothermic Processes','Determine direction of energy transfer and sign of heat.'],['6.2','Energy Diagrams','Represent relative energies and enthalpy changes.'],['6.3','Heat Transfer and Thermal Equilibrium','Apply energy conservation to thermal equilibrium.'],['6.4','Heat Capacity and Calorimetry','Calculate heat transfer from calorimetry data.'],['6.5','Energy of Phase Changes','Calculate energy during temperature and phase changes.'],['6.6','Introduction to Enthalpy of Reaction','Relate reaction enthalpy to heat at constant pressure.'],['6.7','Bond Enthalpies','Estimate reaction enthalpy from bonds broken and formed.'],['6.8','Enthalpy of Formation','Calculate reaction enthalpy from formation data.'],['6.9','Hess’s Law','Combine thermochemical equations to find enthalpy change.']]},
 {name:'Equilibrium',weight:'7-9%',periods:'11-14',understanding:'At dynamic equilibrium, opposing processes continue at equal rates and macroscopic properties remain constant.',question:'How do competing processes establish balance and respond to a disturbance?',practices:'Construct equilibrium expressions, compare Q and K, calculate composition, and justify shifts.',tips:'Exclude pure solids and liquids from K and use Q versus K for directional claims.',vocab:['dynamic equilibrium','equilibrium constant','reaction quotient','ICE table','Le Châtelier principle','solubility product','common-ion effect'],topics:[
 ['7.1','Introduction to Equilibrium','Explain dynamic equilibrium using equal forward and reverse rates.'],['7.2','Direction of Reversible Reactions','Predict net reaction direction from composition.'],['7.3','Reaction Quotient and Equilibrium Constant','Write Q and K expressions and predict direction.'],['7.4','Calculating the Equilibrium Constant','Determine K from equilibrium data.'],['7.5','Magnitude of the Equilibrium Constant','Interpret K as product or reactant favorability.'],['7.6','Properties of the Equilibrium Constant','Transform K when equations are manipulated.'],['7.7','Calculating Equilibrium Concentrations','Use stoichiometry and ICE tables.'],['7.8','Representations of Equilibrium','Connect particle, graphical, and mathematical representations.'],['7.9','Introduction to Le Châtelier’s Principle','Predict effects of concentration, pressure, and volume changes.'],['7.10','Reaction Quotient and Le Châtelier’s Principle','Use Q and K to justify a system response.'],['7.11','Introduction to Solubility Equilibria','Write Ksp expressions and calculate ion concentrations.'],['7.12','Common-Ion Effect','Explain how a common ion changes equilibrium composition.']]},
 {name:'Acids and Bases',weight:'11-15%',periods:'18-22',understanding:'Acid-base behavior is governed by proton transfer, molecular structure, and equilibrium.',question:'What determines acid-base strength, pH, buffering, and titration behavior?',practices:'Represent proton transfer, calculate pH, interpret titration curves, and design buffers.',tips:'Distinguish strength from concentration and identify dominant species before choosing an equation.',vocab:['Brønsted-Lowry acid','conjugate pair','amphiprotic','pH','pKa','strong acid','weak acid','buffer','Henderson-Hasselbalch equation','titration curve','equivalence point','acid-base indicator'],topics:[
 ['8.1','Introduction to Acids and Bases','Identify acids, bases, and conjugate pairs.'],['8.2','pH and pOH of Strong Acids and Bases','Calculate pH, pOH, and ion concentrations.'],['8.3','Weak Acid and Base Equilibria','Calculate equilibrium composition using Ka or Kb.'],['8.4','Acid-Base Reactions and Buffers','Explain buffer action through conjugate-pair reactions.'],['8.5','Acid-Base Titrations','Use stoichiometry and equilibrium across a titration.'],['8.6','Molecular Structure of Acids and Bases','Explain strength using structure and conjugate stability.'],['8.7','pH and pKa','Relate pH, pKa, and conjugate-pair amounts.'],['8.8','Properties of Buffers','Calculate buffer pH and predict response to additions.'],['8.9','Henderson-Hasselbalch Equation','Apply the equation within its assumptions.'],['8.10','Buffer Capacity','Explain how concentration and ratio affect capacity.'],['8.11','Acid-Base Indicators','Select an indicator for an equivalence region.']]},
 {name:'Thermodynamics and Electrochemistry',weight:'7-9%',periods:'11-14',understanding:'Entropy and Gibbs energy predict favorability; electrochemical cells convert chemical and electrical energy.',question:'What determines thermodynamic favorability and electrochemical work?',practices:'Calculate entropy and Gibbs energy, connect thermodynamics to equilibrium, and analyze cells.',tips:'Favorability does not imply speed; carefully track electron flow, signs, and reaction direction.',vocab:['entropy','microstate','Gibbs free energy','thermodynamically favored','galvanic cell','electrolytic cell','anode','cathode','cell potential','Faraday constant','Nernst equation'],topics:[
 ['9.1','Introduction to Entropy','Relate entropy to energy dispersal and microstates.'],['9.2','Absolute Entropy and Entropy Change','Calculate and predict entropy changes.'],['9.3','Gibbs Free Energy and Thermodynamic Favorability','Use Gibbs energy to determine favorability.'],['9.4','Thermodynamic and Kinetic Control','Distinguish favorability from reaction rate.'],['9.5','Free Energy and Equilibrium','Connect standard Gibbs energy, K, and equilibrium.'],['9.6','Coupled Reactions','Explain how a favorable process drives an unfavorable one.'],['9.7','Galvanic (Voltaic) and Electrolytic Cells','Compare spontaneous and externally driven cells.'],['9.8','Cell Potential and Free Energy','Connect cell potential to Gibbs energy.'],['9.9','Cell Potential Under Nonstandard Conditions','Predict potential under nonstandard conditions.'],['9.10','Electrolysis and Faraday’s Law','Calculate charge, current, time, and product amount.'],['9.11','Applications of Electrochemistry','Analyze batteries, fuel cells, corrosion, and electroplating.']]}
];

const colors=['#38bdf8','#a78bfa','#34d399','#f59e0b','#f472b6','#22d3ee','#fb7185','#84cc16','#c084fc'];
const average=(w:string)=>{const [a,b=a]=w.replace('%','').split('-').map(Number);return(a+b)/2};
const total=seeds.reduce((s,u)=>s+average(u.weight),0);
export const vocabularyDefs:Record<string,string>={};
seeds.forEach(u=>u.vocab.forEach(term=>{vocabularyDefs[term]=`A core AP Chemistry term for ${u.name.toLowerCase()}. Explain it with a particle-level model, relevant evidence, and any applicable quantitative relationship.`}));

export const courseData:CourseData={units:seeds.map((u,i)=>({
 id:`unit-${i+1}`,name:`Unit ${i+1}: ${u.name}`,examWeighting:u.weight,normalizedWeight:average(u.weight)/total,classPeriods:u.periods,color:colors[i],keyUnderstanding:u.understanding,
 bigIdeas:[{title:'Structure and Change',question:u.question}],sciencePractices:u.practices,examTips:u.tips,vocabulary:u.vocab,
 topics:u.topics.map(([number,title,objective],j)=>({id:`u${i+1}t${j+1}`,name:`Topic ${number}: ${title}`,iCanStatements:[{id:`u${i+1}t${j+1}ic1`,text:objective,keyConcepts:[
  {id:`u${i+1}t${j+1}ic1kc1`,text:`Explain ${title.toLowerCase()} using particle-level models and precise chemical reasoning.`},
  {id:`u${i+1}t${j+1}ic1kc2`,text:`Analyze an AP-style representation or calculation involving ${title.toLowerCase()} and justify the result.`}
 ]}]}))
}))};
