import React from 'react';
import { courseData } from '../constants';

const examSource='https://apcentral.collegeboard.org/courses/ap-chemistry/exam';
const datesSource='https://apstudents.collegeboard.org/exam-dates';
const equationsSource='https://apcentral.collegeboard.org/media/pdf/ap-chemistry-equations-sheet.pdf';
const cedSource='https://apcentral.collegeboard.org/media/pdf/ap-chemistry-course-and-exam-description.pdf';

const ExamGuide:React.FC=()=> <main className="exam-poster mx-auto max-w-7xl px-4 py-8">
 <section className="mb-7 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl">
  <div className="flex h-2">{courseData.units.map(u=><span key={u.id} className="flex-1" style={{backgroundColor:u.color}} />)}</div>
  <div className="p-6 sm:p-8"><p className="mb-2 text-sm font-bold uppercase tracking-[0.18em] text-cyan-600">2027 AP Chemistry Exam</p><h2 className="text-3xl font-black text-slate-950 sm:text-4xl">Thursday, May 6, 2027</h2><p className="mt-2 text-lg font-semibold text-slate-600">Session 2 · Hybrid digital · 3 hours 15 minutes</p></div>
 </section>
 <section className="mb-6 grid gap-5 lg:grid-cols-2">
  <article className="rounded-2xl border-t-4 border-cyan-400 bg-white p-6 shadow-md"><div className="flex justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-wider text-cyan-700">Section I</p><h3 className="mt-1 text-2xl font-black text-slate-950">Multiple Choice</h3></div><span className="h-fit rounded-full bg-cyan-100 px-3 py-1 text-sm font-bold text-cyan-800">50%</span></div><div className="my-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-100 p-4"><p className="text-3xl font-black text-slate-950">60</p><p className="text-sm text-slate-600">questions</p></div><div className="rounded-xl bg-slate-100 p-4"><p className="text-3xl font-black text-slate-950">90</p><p className="text-sm text-slate-600">minutes</p></div></div><ul className="list-disc space-y-2 pl-5 text-slate-700"><li>Completed in the Bluebook testing app.</li><li>Includes discrete questions and stimulus or data sets.</li><li>A scientific or graphing calculator is recommended.</li></ul></article>
  <article className="rounded-2xl border-t-4 border-violet-400 bg-white p-6 shadow-md"><div className="flex justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-wider text-violet-700">Section II</p><h3 className="mt-1 text-2xl font-black text-slate-950">Free Response</h3></div><span className="h-fit rounded-full bg-violet-100 px-3 py-1 text-sm font-bold text-violet-800">50%</span></div><div className="my-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-100 p-4"><p className="text-3xl font-black text-slate-950">7</p><p className="text-sm text-slate-600">questions</p></div><div className="rounded-xl bg-slate-100 p-4"><p className="text-3xl font-black text-slate-950">105</p><p className="text-sm text-slate-600">minutes</p></div></div><ul className="list-disc space-y-2 pl-5 text-slate-700"><li>Prompts appear in Bluebook; responses are handwritten.</li><li>3 long questions worth 10 points each.</li><li>4 short questions worth 4 points each.</li></ul></article>
 </section>
 <section className="mb-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-black text-slate-950">Course skills assessed</h3><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{['Models and representations','Question and method','Representing data and phenomena','Model analysis','Mathematical routines','Argumentation'].map((s,i)=><div key={s} className="rounded-xl bg-slate-100 p-4"><p className="text-xs font-bold text-cyan-700">SKILL {i+1}</p><p className="mt-1 font-bold text-slate-900">{s}</p></div>)}</div></section>
 <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-black text-slate-950">Exam-day essentials</h3><div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl bg-slate-100 p-4"><p className="font-bold text-slate-900">Hybrid digital</p><p className="mt-1 text-sm text-slate-600">Questions appear in Bluebook; FRQ answers go in a paper booklet.</p></div><div className="rounded-xl bg-slate-100 p-4"><p className="font-bold text-slate-900">Calculator permitted</p><p className="mt-1 text-sm text-slate-600">Bring an approved scientific or graphing calculator.</p></div><a className="rounded-xl border-2 border-cyan-300 bg-cyan-50 p-4 transition hover:bg-cyan-100" href={equationsSource} target="_blank" rel="noreferrer"><p className="font-bold text-cyan-900">Reference information ↗</p><p className="mt-1 text-sm text-cyan-800">Open the official equations, constants, and periodic table sheet.</p></a><a className="rounded-xl border-2 border-violet-300 bg-violet-50 p-4 transition hover:bg-violet-100" href={cedSource} target="_blank" rel="noreferrer"><p className="font-bold text-violet-900">Course framework ↗</p><p className="mt-1 text-sm text-violet-800">Open the official AP Chemistry CED.</p></a></div><p className="mt-5 text-sm text-slate-500">Official sources: <a className="font-semibold text-cyan-700 underline" href={examSource} target="_blank" rel="noreferrer">exam format</a> · <a className="font-semibold text-cyan-700 underline" href={datesSource} target="_blank" rel="noreferrer">2027 exam dates</a></p></section>
</main>;

export default ExamGuide;
